!<AUTO_GENERATION_HEADER>!

#include <cstdint>
#include "tdm_stub.hpp"

namespace tdm {

/***************************** STATIC CONSTANTS *****************************/

const scheduleType_e BaseTdmScheduler::kScheduleType = !<SCHEDULE_TYPE>!;
const uint32_t BaseTdmScheduler::kCycleSize = !<CYCLE_SIZE>!;
const uint32_t BaseTdmScheduler::kNumberOfTasks = !<NUMBER_OF_TASKS>!;

/***************************** GENERATED METHODS *****************************/

void BaseTdmScheduler::executeCall()
{
    tdmTaskId_e taskToExecute = getTaskToExecute();
    switch (taskToExecute)
    {
!<EXECUTION_CALLS>!
    default:
        {
            // Do nothing, invalid ID
        }
    }
}

tdmTaskId_e BaseTdmScheduler::getTaskAtTimeQuantaFromJson(uint32_t timeQuanta)
{
    !<GET_TASK_QUANTA_FROM_JSON>!
}

/***************************** AUTOGENERATED TASK DATA *****************************/
const tdmTaskId_e BaseTdmScheduler::kScheduleTable[BaseTdmScheduler::kCycleSize] = {
!<SCHEDULING_TABLE>!
};

const tdmTaskData_t BaseTdmScheduler::kTaskData[BaseTdmScheduler::kNumberOfTasks] = {
!<TASK_DATA>!
};

} // namespace tdm
