"""Emit the C++ ``!<...>!`` stub tokens from a validated schedule.

This is the final stage of the code generator. It consumes the canonical
:class:`~tdm_schedule_model.ScheduleModel` (produced by :func:`tdm_schedule_model.load_schedule`)
and the tick-indexed table (produced by :func:`tdm_schedule_table.build_schedule_table`) and renders
the text that replaces each ``!<TOKEN>!`` placeholder in the stub templates under ``src/stubs``.

The scheduler-derived tokens come straight from the model/table:

* ``!<TASK_ID_TYPEDEF>!``          — ``tdmTaskId_<id>`` enumerators, one per task.
* ``!<SCHEDULING_TABLE>!``         — the flat ``kScheduleTable`` initializer, one entry per tick.
* ``!<EXECUTION_CALLS>!``          — a ``switch`` case per task dispatching its function.
* ``!<TASK_DATA>!``               — the ``kTaskData`` initializer, one entry per task.
* ``!<GET_TASK_QUANTA_FROM_JSON>!``— computed per-quanta lookup body (``json`` schedule type).
* ``!<CYCLE_SIZE>!``              — ``kCycleSize`` (== ``cycle_ticks``).
* ``!<NUMBER_OF_TASKS>!``          — ``kNumberOfTasks`` (task count, sizes ``kTaskData``).
* ``!<SCHEDULE_TYPE>!``            — the ``scheduleType_e`` enumerator.

The remaining tokens are user configuration with sensible defaults, carried on
:class:`GeneratorOptions`: ``!<AUTO_GENERATION_HEADER>!``, ``!<TDM_NAMESPACE>!``,
``!<PROFILER_NAMESPACE>!``, ``!<QUANTA_UNIT>!``, ``!<PATH_TO_HEADER>!``.

Dependency-free: standard library only. Run ``python3 generator/tdm_schedule_generation.py --help``.
"""

from __future__ import annotations

import argparse
import os
import re
from dataclasses import dataclass
from typing import Dict, List, Optional

from tdm_schedule_model import ScheduleModel, load_schedule
from tdm_schedule_table import build_schedule_table

# The reserved idle enumerator, always emitted first in the typedef and used for idle ticks.
IDLE_TASK_ID = "tdmTaskId_Idle"

# SCHEDULE_TYPE string -> scheduleType_e enumerator (see tdm_base.hpp).
_SCHEDULE_TYPE_ENUM = {
    "table": "tdmScheduleType_table",
    "json": "tdmScheduleType_json",
    "custom": "tdmScheduleType_custom",
}


class GenerationError(Exception):
    """Raised when a template cannot be rendered (e.g. an unrecognized ``!<...>!`` token)."""


@dataclass(frozen=True)
class GeneratorOptions:
    """User-configurable, non-schedule inputs to generation, each with a portable default.

    These map to the tokens that the README describes as "user string input"; the scheduler-derived
    tokens are computed from the model and are not configurable here.
    """

    schedule_type: str = "table"  # one of _SCHEDULE_TYPE_ENUM
    tdm_namespace: str = "tdm"
    profiler_namespace: str = "tdm"
    quanta_unit: str = "unsigned int"
    path_to_header: str = ""

    def validate(self) -> None:
        if self.schedule_type not in _SCHEDULE_TYPE_ENUM:
            raise GenerationError(
                f"schedule_type must be one of {sorted(_SCHEDULE_TYPE_ENUM)}, "
                f"got {self.schedule_type!r}"
            )


def _task_id(identifier: str) -> str:
    """The C enumerator for a task identifier, e.g. ``Task_100Hz`` -> ``tdmTaskId_Task_100Hz``."""
    return f"tdmTaskId_{identifier}"


# --------------------------------------------------------------------------------------------------
# Token renderers. Each returns the text for one token. Block tokens (those that occupy a whole line
# in the template) return content already indented as it should appear in the output; render_template
# preserves that by prefixing the template line's own indentation. Inline tokens return a single line.
# --------------------------------------------------------------------------------------------------


def render_auto_generation_header(model: ScheduleModel) -> str:
    """The do-not-edit banner inserted at the top of each generated file."""
    return (
        "/*\n"
        " * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.\n"
        " *\n"
        f" * Generated by the TDM code generator from schedule {model.name!r}.\n"
        " * Edit the schedule JSON and re-run the generator to change this file.\n"
        " */"
    )


def render_task_id_typedef(model: ScheduleModel) -> str:
    """The ``tdmTaskId_e`` enumerators for each task (``tdmTaskId_Idle`` is in the stub already)."""
    return "\n".join(f"    {_task_id(task.identifier)}," for task in model.tasks)


def render_scheduling_table(
    table: List[Optional[str]], row_width: Optional[int] = None
) -> str:
    """The ``kScheduleTable`` initializer: one ``tdmTaskId_*`` entry per tick.

    Entries are laid out ``row_width`` per line (defaulting to the sub-cycle width when known) with a
    leading ``/* tick N */`` comment so a human can find any tick in the array quickly.
    """
    width = row_width if row_width and row_width > 0 else 16
    lines: List[str] = []
    for start in range(0, len(table), width):
        row = table[start:start + width]
        entries = ", ".join(_task_id(name) if name is not None else IDLE_TASK_ID for name in row)
        lines.append(f"    /* tick {start} */ {entries},")
    return "\n".join(lines)


def render_execution_calls(model: ScheduleModel) -> str:
    """A ``switch`` case per task: set the executing task, call it, then reset to idle."""
    blocks: List[str] = []
    for task in model.tasks:
        task_id = _task_id(task.identifier)
        blocks.append(
            f"    case ({task_id}): {{\n"
            f"        setCurrentExecutingTask({task_id});\n"
            f"        taskFunction_{task.identifier}();\n"
            f"        setCurrentExecutingTask({IDLE_TASK_ID});\n"
            f"        break;\n"
            f"    }}"
        )
    return "\n".join(blocks)


def render_task_data(model: ScheduleModel) -> str:
    """The ``kTaskData`` initializer: one entry per task (the profiler is default-constructed)."""
    return "\n".join(
        f"    {{ {_task_id(task.identifier)} }}, /* {task.name} */" for task in model.tasks
    )


def render_get_task_quanta_from_json(model: ScheduleModel) -> str:
    """Body of ``getTaskAtTimeQuantaFromJson``: compute the owning task for a quanta on the fly.

    Rather than a flat table, the ``json`` schedule type stores each task's ``{start, period,
    assigned}`` and derives ownership at runtime: a task owns ``timeQuanta`` when the phase of that
    quanta within the task's period falls inside its assigned window. The schedule is validated
    conflict-free, so at most one task matches; otherwise the tick is idle.
    """
    entries = "\n".join(
        f"        {{ {_task_id(task.identifier)}, {task.start_tick}, "
        f"{task.period_ticks}, {task.assigned_ticks} }},"
        for task in model.tasks
    )
    return (
        "static const struct {\n"
        "    tdmTaskId_e id;\n"
        "    uint32_t start;\n"
        "    uint32_t period;\n"
        "    uint32_t assigned;\n"
        "} kJsonSchedule[] = {\n"
        f"{entries}\n"
        "};\n"
        "\n"
        "for (uint32_t i = 0; i < sizeof(kJsonSchedule) / sizeof(kJsonSchedule[0]); ++i) {\n"
        "    uint32_t phaseInPeriod = timeQuanta % kJsonSchedule[i].period;\n"
        "    uint32_t offset = (phaseInPeriod >= kJsonSchedule[i].start)\n"
        "                          ? (phaseInPeriod - kJsonSchedule[i].start)\n"
        "                          : (phaseInPeriod + kJsonSchedule[i].period - kJsonSchedule[i].start);\n"
        "    if (offset < kJsonSchedule[i].assigned) {\n"
        "        return kJsonSchedule[i].id;\n"
        "    }\n"
        "}\n"
        "return tdmTaskId_Idle;"
    )


def build_token_map(model: ScheduleModel, options: GeneratorOptions) -> Dict[str, str]:
    """Render every supported token for ``model`` under ``options`` into a ``{token: text}`` map.

    Raises :class:`~tdm_schedule_table.TableGenerationError` if the tasks cannot be placed into a
    conflict-free table, and :class:`GenerationError` for invalid options.
    """
    options.validate()
    table = build_schedule_table(model)
    return {
        "AUTO_GENERATION_HEADER": render_auto_generation_header(model),
        "TASK_ID_TYPEDEF": render_task_id_typedef(model),
        "SCHEDULING_TABLE": render_scheduling_table(table, model.sub_cycle_ticks),
        "EXECUTION_CALLS": render_execution_calls(model),
        "TASK_DATA": render_task_data(model),
        "GET_TASK_QUANTA_FROM_JSON": render_get_task_quanta_from_json(model),
        "CYCLE_SIZE": str(model.cycle_ticks),
        "NUMBER_OF_TASKS": str(len(model.tasks)),
        "SCHEDULE_TYPE": _SCHEDULE_TYPE_ENUM[options.schedule_type],
        "TDM_NAMESPACE": options.tdm_namespace,
        "PROFILER_NAMESPACE": options.profiler_namespace,
        "QUANTA_UNIT": options.quanta_unit,
        "PATH_TO_HEADER": options.path_to_header,
    }


# Matches any leftover placeholder so an unhandled token surfaces loudly rather than silently.
_TOKEN_RE = re.compile(r"!<[^>]+>!")


def render_template(text: str, token_map: Dict[str, str]) -> str:
    """Substitute every ``!<TOKEN>!`` in ``text`` with its rendered value.

    A token that occupies a whole line (a *block* token) is replaced with each rendered line prefixed
    by that line's own indentation, so multi-line output nests correctly under whatever indentation
    the template placed the placeholder at. All other occurrences are replaced inline.

    Raises :class:`GenerationError` if any unrecognized placeholder remains after substitution.
    """
    for token, value in token_map.items():
        block = re.compile(rf"^([ \t]*)!<{re.escape(token)}>![ \t]*$", re.MULTILINE)

        def _replace_block(match: "re.Match[str]") -> str:
            indent = match.group(1)
            return "\n".join(indent + line if line else line for line in value.split("\n"))

        text, replaced = block.subn(_replace_block, text)
        if replaced == 0:
            text = text.replace(f"!<{token}>!", value)

    leftover = sorted(set(_TOKEN_RE.findall(text)))
    if leftover:
        raise GenerationError(f"template has unrecognized tokens: {', '.join(leftover)}")
    return text


def _output_name(stub_name: str) -> str:
    """Map a stub filename to its generated counterpart, e.g. ``tdm_stub.cpp`` -> ``tdm.cpp``."""
    return stub_name.replace("_stub", "")


def generate_files(
    model: ScheduleModel,
    options: GeneratorOptions,
    stub_dir: str,
    out_dir: str,
) -> List[str]:
    """Render every ``*_stub.*`` template in ``stub_dir`` into ``out_dir``; return the paths written."""
    token_map = build_token_map(model, options)
    os.makedirs(out_dir, exist_ok=True)
    written: List[str] = []
    for stub_name in sorted(os.listdir(stub_dir)):
        if "_stub." not in stub_name:
            continue
        with open(os.path.join(stub_dir, stub_name), "r", encoding="utf-8") as handle:
            rendered = render_template(handle.read(), token_map)
        out_path = os.path.join(out_dir, _output_name(stub_name))
        with open(out_path, "w", encoding="utf-8") as handle:
            handle.write(rendered)
        written.append(out_path)
    return written


def _default_path(*parts: str) -> str:
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, *parts))


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Generate TDM C++ sources from a schedule JSON.")
    parser.add_argument("schedule", help="path to the schedule JSON definition")
    parser.add_argument(
        "--schema", default=_default_path("tdm_schedule_schema.json"),
        help="path to the schedule JSON schema (default: alongside this script)",
    )
    parser.add_argument(
        "--stubs", default=_default_path("..", "src", "stubs"),
        help="directory of *_stub.* templates (default: ../src/stubs)",
    )
    parser.add_argument(
        "--out", default=_default_path("..", "src", "generated"),
        help="directory to write generated sources into (default: ../src/generated)",
    )
    parser.add_argument("--schedule-type", default="table", choices=sorted(_SCHEDULE_TYPE_ENUM))
    parser.add_argument("--tdm-namespace", default="tdm")
    parser.add_argument("--profiler-namespace", default="tdm")
    parser.add_argument("--quanta-unit", default="unsigned int")
    parser.add_argument("--path-to-header", default="")
    args = parser.parse_args(argv)

    options = GeneratorOptions(
        schedule_type=args.schedule_type,
        tdm_namespace=args.tdm_namespace,
        profiler_namespace=args.profiler_namespace,
        quanta_unit=args.quanta_unit,
        path_to_header=args.path_to_header,
    )

    model = load_schedule(args.schedule, args.schema)
    written = generate_files(model, options, args.stubs, args.out)
    for path in written:
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
