
!<AUTO_GENERATION_HEADER>!

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/***************************** TYPEDEFS *****************************/

typedef enum tdmTaskId_ {
    tdmTaskId_Idle;
!<TASK_ID_TYPEDEF>!
} tdmTaskId_e;


typedef taskData_ {
    tdmTaskId_e id;


} taskData_t;

typedef scheduleType_ {
    tdmScheduleType_table;
    tdmScheduleType_json;
    tdmScheduleType_custom;
} scheduleType_e;

/***************************** CONSTANTS *****************************/

/**
 * @brief The number of time-quanta in the scheduling cycle
 */
extern const !<QUANTA_UNIT>! kCycleSize = !<CYCLE_SIZE>!;

/**
 * @brief Autogenerated task schedule table
 */
extern const tdmTaskId_e kScheduleTable[kCycleSize];

/**
 * @brief Autogenerated constant to determine what method to get the task
 * schedule from; table, JSON, or custom
 */
extern const scheduleType_e kScheduleType;

/***************************** AUTOGENERATED TASK DATA *****************************/

!<TASK_DATA_DECLARATIONS>!

/***************************** GLOBAL VARIABLES *****************************/

extern tdmTaskId_e g_currentExecutingTask;
extern tdmTaskId_e g_taskToExecute;
extern tdmTaskId_e g_lastAllocatedTask;
extern !<QUANTA_UNIT>! g_currentTimeQuanta;
extern !<QUANTA_UNIT>! g_overrunTimeQuanta;

/***************************** FUNCTIONS *****************************/

void tdmScheduleCall();

/**
 * @brief AUTOGENERATED function t 
 */
void tdmExecuteCall();

tdmTaskId_e getTaskAtTimeQuanta(!<QUANTA_UNIT>! timeQuanta);

/**
 * @brief Read the task allocation at the given time quanta from the TDM
 * schedule table.
 */
tdmTaskId_e getTaskAtTimeQuantaFromTable(!<QUANTA_UNIT>! timeQuanta);

/**
 * @brief AUTOGENERATED calculate the task allocation at the given time quanta
 * from the task-defintion JSON data. This uses the periodicity, start quanta,
 * and period parameters from each task to calculate it programmatically, rather
 * than from a large table in the executable
 */
tdmTaskId_e getTaskAtTimeQuantaFromJson(!<QUANTA_UNIT>! timeQuanta);

/***************************** USER-IMPLEMENTED EXTERN FUNCTIONS *****************************/

/**
 * @brief User-implemented function to perform a thread-safe SET of g_currentExecutingTask
 */
extern void setCurrentExecutingTask(tdmTaskId_e taskId);
/**
 * @brief User-implemented function to perform a thread-safe SET of g_taskToExecute
 */
extern void setTaskToExecute(tdmTaskId_e taskId);
/**
 * @brief User-implemented function to perform a thread-safe GET of g_currentExecutingTask
 */
extern tdmTaskId_e getCurrentExecutingTask();
/**
 * @brief User-implemented function to perform a thread-safe GET of g_taskToExecute
 */
extern tdmTaskId_e getTaskToExecute();
/**
 * @brief User-implemented function to report a TDM scheduling overrun error
 */
extern void raiseTdmSchedulingError();
/**
 * @brief Optional user-implemented function to implement a custom function to calculate the task allocation
 * at the given time quanta. This may used instead of the getTaskAtTimeQuantaFromTable 
 * or getTaskAtTimeQuantaFromJson functions.
 */
extern tdmTaskId_e getTaskAtTimeQuantaFromCustom(!<QUANTA_UNIT>! timeQuanta);


#ifdef __cplusplus
}
#endif
