!<AUTO_GENERATION_HEADER>!
#include <stdint.h>
#include "tdm.hpp"

/***************************** GLOBAL VARIABLES *****************************/

const scheduleType_e kScheduleType = !<SCHEDULE_TYPE>!

tdmTaskId_e g_currentRunningTask = tdmTaskId_Idle
tdmTaskId_e g_taskToExecute = tdmTaskId_Idle
tdmTaskId_e g_lastAllocatedTask = tdmTaskId_Idle;
!<QUANTA_UNIT>! g_currentTimeQuanta = 0;
!<QUANTA_UNIT>! g_overrunTimeQuanta = 0;


/***************************** FUNCTIONS *****************************/

bool tdmScheduleCall() {
    // Boolean to indicate whether the execution thread should be triggered
    // to execute a task
    bool triggerNewTask = false;

    // Get the task that is allocated for this time quanta
    tdmTaskId_e allocatedTask = getTaskAtTimeQuanta(g_currentTimeQuanta);

    // Check if a task is running that shouldnt be at this time quanta,
    // excluding idle
    if ((taskAtCurrentQuanta != getCurrentExecutingTask()) &&
        (g_currentRunningTask != tdmTaskId_Idle)) {
        // ERROR HERE!!!
        // Dont increment the time quanta, wait another tick until the running task is done 
        g_overrungTimeQuanta++;
        raiseTdmSchedulingError();
    } else {
        // No unexpected task execution, normal operation

        // Detect edge change, trigger task execution if edge is the start of a new
        // contiguous task allocation
        if ((g_lastAllocatedTask != allocatedTask) &&
            (currentAllocatedTask != tdmTaskId_Idle)) {

            setGlobalTaskToExecute(allocatedTask);
            triggerNewTask = true;
        }

        // Increment time quanta, wrap around max value
        g_currentTimeQuanta++;
        if (g_currentTimeQuanta >= kCycleSize) {
            g_currentTimeQuanta = 0;
        }

        // Cache task allocation to detect edge change at next call
        g_lastAllocatedTask = allocatedTask;
    }
    return triggerNewTask;
}

void tdmExecuteCall() {
    tdmTaskId_e taskToExecute = getTaskToExecute();
    switch (taskToExecute) {
!<EXECUTION_CALLS>!
        default: {
            // Do nothing, invalid ID
        }
    }
}


tdmTaskId_e getTaskAtTimeQuanta(!<QUANTA_UNIT>! timeQuanta) {
    tdmTaskId_e task;

    switch(kScheduleType) {
        case(tdmScheduleType_table): {
            task = getTaskAtTimeQuantaFromTable(timeQuanta);
            break;
        }
        case(tdmScheduleType_json): {
            task = getTaskAtTimeQuantaFromJson(timeQuanta);
            break;
        }
        case(tdmScheduleType_custom): {
            task = getTaskAtTimeQuantaFromCustom(timeQuanta);
            break;
        }
        default: {
            // Error
            task = tdmTaskId_Idle;
            break;
        }
    }
    return task;
}

tdmTaskId_e getTaskAtTimeQuantaFromTable(!<QUANTA_UNIT>! timeQuanta) {
    return kScheduleTable[timeQuanta];
}

tdmTaskId_e getTaskAtTimeQuantaFromJson(!<QUANTA_UNIT>! timeQuanta) {
!<GET_TASK_QUANTA_FROM_JSON>!
}

/***************************** AUTOGENERATED TASK DATA *****************************/
!<TASK_DATA_DEFINTIONS>!

const tdmTaskId_e kScheduleTable[kCycleSize] = {
!<SCHEDULING_TABLE>!
};
